apiVersion: observability.openshift.io/v1beta1
kind: LogForwarder
metadata:
  name: collector
spec:
  input:
    collectionPolicy:
      distributionClass: highpriority
    container:
      selector:
        priority: high
      excludes: ["servicemesh*"]
  outputs:
  - name: namespaced-http
    type: http
    http:
      url: http://http-receiver:8090
    tls:
      insecureSkipVerify: true