apiVersion: observability.openshift.io/v1beta1
kind: ClusterLogDistributor
metadata:
  name: infra
spec:
  managementState: Managed
  priority: 10
  collectionPolicy:
    container:
      includes:
        - namespace: userinfra*
        - namespace: openshift*
        - namespace: default
        - namespace: kube*
