apiVersion: observability.openshift.io/v1beta1
kind: ClusterLogDistributor
metadata:
  name: default
spec:
  managementState: Managed
  priority: 1
  collectionPolicy:
    container:
      includes:
        - namespace: openshift*
        - namespace: default
        - namespace: kube*
