//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/openshift/cluster-logging-operator/api/observability/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLogDistributor) DeepCopyInto(out *ClusterLogDistributor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLogDistributor.
func (in *ClusterLogDistributor) DeepCopy() *ClusterLogDistributor {
	if in == nil {
		return nil
	}
	out := new(ClusterLogDistributor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterLogDistributor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLogDistributorCollectionPolicySpec) DeepCopyInto(out *ClusterLogDistributorCollectionPolicySpec) {
	*out = *in
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(ClusterLogDistributorContainerInputSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLogDistributorCollectionPolicySpec.
func (in *ClusterLogDistributorCollectionPolicySpec) DeepCopy() *ClusterLogDistributorCollectionPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterLogDistributorCollectionPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLogDistributorContainerInputSpec) DeepCopyInto(out *ClusterLogDistributorContainerInputSpec) {
	*out = *in
	if in.Includes != nil {
		in, out := &in.Includes, &out.Includes
		*out = make([]v1.NamespaceContainerSpec, len(*in))
		copy(*out, *in)
	}
	if in.Excludes != nil {
		in, out := &in.Excludes, &out.Excludes
		*out = make([]v1.NamespaceContainerSpec, len(*in))
		copy(*out, *in)
	}
	if in.NamespaceMatchLabels != nil {
		in, out := &in.NamespaceMatchLabels, &out.NamespaceMatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLogDistributorContainerInputSpec.
func (in *ClusterLogDistributorContainerInputSpec) DeepCopy() *ClusterLogDistributorContainerInputSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterLogDistributorContainerInputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLogDistributorList) DeepCopyInto(out *ClusterLogDistributorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterLogDistributor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLogDistributorList.
func (in *ClusterLogDistributorList) DeepCopy() *ClusterLogDistributorList {
	if in == nil {
		return nil
	}
	out := new(ClusterLogDistributorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterLogDistributorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLogDistributorSpec) DeepCopyInto(out *ClusterLogDistributorSpec) {
	*out = *in
	if in.Collector != nil {
		in, out := &in.Collector, &out.Collector
		*out = new(v1.CollectorSpec)
		(*in).DeepCopyInto(*out)
	}
	in.CollectionPolicy.DeepCopyInto(&out.CollectionPolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLogDistributorSpec.
func (in *ClusterLogDistributorSpec) DeepCopy() *ClusterLogDistributorSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterLogDistributorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterLogDistributorStatus) DeepCopyInto(out *ClusterLogDistributorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterLogDistributorStatus.
func (in *ClusterLogDistributorStatus) DeepCopy() *ClusterLogDistributorStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterLogDistributorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectionPolicy) DeepCopyInto(out *CollectionPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectionPolicy.
func (in *CollectionPolicy) DeepCopy() *CollectionPolicy {
	if in == nil {
		return nil
	}
	out := new(CollectionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerInputSpec) DeepCopyInto(out *ContainerInputSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Includes != nil {
		in, out := &in.Includes, &out.Includes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Excludes != nil {
		in, out := &in.Excludes, &out.Excludes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerInputSpec.
func (in *ContainerInputSpec) DeepCopy() *ContainerInputSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerInputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogForwarder) DeepCopyInto(out *LogForwarder) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogForwarder.
func (in *LogForwarder) DeepCopy() *LogForwarder {
	if in == nil {
		return nil
	}
	out := new(LogForwarder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogForwarder) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogForwarderInputSpec) DeepCopyInto(out *LogForwarderInputSpec) {
	*out = *in
	if in.Container != nil {
		in, out := &in.Container, &out.Container
		*out = new(ContainerInputSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CollectionPolicy != nil {
		in, out := &in.CollectionPolicy, &out.CollectionPolicy
		*out = new(CollectionPolicy)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogForwarderInputSpec.
func (in *LogForwarderInputSpec) DeepCopy() *LogForwarderInputSpec {
	if in == nil {
		return nil
	}
	out := new(LogForwarderInputSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogForwarderList) DeepCopyInto(out *LogForwarderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LogForwarder, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogForwarderList.
func (in *LogForwarderList) DeepCopy() *LogForwarderList {
	if in == nil {
		return nil
	}
	out := new(LogForwarderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogForwarderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogForwarderSpec) DeepCopyInto(out *LogForwarderSpec) {
	*out = *in
	if in.Forwarder != nil {
		in, out := &in.Forwarder, &out.Forwarder
		*out = new(v1.CollectorSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Input.DeepCopyInto(&out.Input)
	if in.Outputs != nil {
		in, out := &in.Outputs, &out.Outputs
		*out = make([]v1.OutputSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceAccount != nil {
		in, out := &in.ServiceAccount, &out.ServiceAccount
		*out = new(v1.ServiceAccount)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogForwarderSpec.
func (in *LogForwarderSpec) DeepCopy() *LogForwarderSpec {
	if in == nil {
		return nil
	}
	out := new(LogForwarderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogForwarderStatus) DeepCopyInto(out *LogForwarderStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogForwarderStatus.
func (in *LogForwarderStatus) DeepCopy() *LogForwarderStatus {
	if in == nil {
		return nil
	}
	out := new(LogForwarderStatus)
	in.DeepCopyInto(out)
	return out
}
