apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/logging.openshift.io_clusterlogforwarders.yaml
- bases/logging.openshift.io_clusterloggings.yaml
- bases/logging.openshift.io_logfilemetricexporters.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
#- patches/cainjection_in_logging_clusterlogforwarders.yaml
#- patches/webhook_in_logging_clusterlogforwarders.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

patches:
  - target:
      kind: CustomResourceDefinition
      name: logfilemetricexporters.logging.openshift.io
    patch: |-
      - op: add
        path: /spec/versions/0/schema/openAPIV3Schema/properties/metadata
        value:
          type: object
          properties:
            name:
              type: string
              enum:
              - instance

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
#  - kustomizeconfig.yaml